name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: cmake 
      run:  mkdir build
      run:  cd build
      run:  cmake ../CMakefile.txt 
      run:  make
