name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: cmake dir
      run:  mkdir build 2> /dev/null
    - name:  cd build 
      run:  cd build
    - name:  cmake .
      run:  cmake .
    - name:  make 
      run:  make
